CREATE TABLE `requirements` (
 `ID` int(11) NOT NULL,
 `ProdType` varchar(255) NOT NULL,
 `Title` varchar(255) NOT NULL,
 `Describe` varchar(2000) NOT NULL,
 `Status` int(11) NOT NULL,
 `OperateUser` varchar(255) NOT NULL DEFAULT '',
 `OperateUserName` varchar(255) NOT NULL DEFAULT '',
 `Uid` varchar(255) DEFAULT '',
 `Uin` varchar(255) NOT NULL,
 `Nickname` varchar(255) NOT NULL DEFAULT '',
 `CreateAt` int(11) NOT NULL,
 `UpdateAt` int(11) NOT NULL,
 `UserType` int(11) NOT NULL,
 `Images` varchar(255) NOT NULL,
 `CurrentStatus` varchar(255) NOT NULL,
 `PicPaths` varchar(255) NOT NULL,
 `FilePaths` varchar(255) NOT NULL,
 `ProdTypeID` int(11) NOT NULL,
 `ApprovedCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '点赞',
 `ReadCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '阅读',
 `CommentCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '评论数',
 `CollectionCount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '收藏',
 PRIMARY KEY (`ID`),
 KEY `Uin` (`Uin`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;